<?php
/**
 * Created by IntelliJ IDEA.
 * User: Simone Sika
 * Date: 15/08/2019
 * Time: 16:56
 */

namespace app\controllers;


class PDFUtils extends \TCPDF
{
    private $footer_text = "";

    public function Footer()
    {
        //parent::Footer(); // TODO: Change the autogenerated stub
        $this->SetFont('helvetica', 'I', 8);
        $this->Write(0, "Banque Atlantique Togo\nS.A. au capital social de F CFA 10 619 260 000 – RCCM TOGO-LOME 2005 B0336 – COE N° 0510960 – Agrément N° T0138 J\nSiège social : Place du Petit Marché, Rue Koumoré – 01 BP 3256 Lomé Tél. : +228 22 20 88 92 / 22 23 08 00 – Fax : +228 22 20 88 93 –\nE-mail : infobatg@banqueatlantique.net",
            '', false, 'L', false, 0, 0, true, 0, '', 'T');
    }


    /**
     * @param \TCPDF $pdf
     * @return \TCPDF
     * @throws \yii\base\Exception
     */
    public static function preparePdf(\TCPDF $pdf)
    {

        $pdf->SetCreator("HABILITE");
        $pdf->SetAuthor("Jeanpaul Tossou");
        $pdf->SetKeywords("Habilite,batg,Banque Atlantique,Togo,signature");
        $pdf->SetTitle('Habilite Pdf Document');

        // set default header data
        $pdf->SetHeaderData('logo.jpg', 50, '', '', array(0, 64, 255), array(255, 255, 255));
        $pdf->setFooterData(array(0, 64, 0), array(0, 64, 128));

        /*var_dump($pdf->getHeaderData());
        die();*/

        // set header and footer fonts
        $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

        // set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // set margins
        $pdf->SetMargins(PDF_MARGIN_LEFT, 40, PDF_MARGIN_RIGHT);
        $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $pdf->SetFooterMargin(20);

        // set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

        // set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

        // ---------------------------------------------------------

        $certificate = "file://" . Utils::getCertificatDir() . 'habilite.tg.crt';
        $certificate_key = "file://" . Utils::getCertificatDir() . 'habilite.tg.key';

        /*var_dump($certificate);
        die();*/

        $info = [
            'Name' => "HABILITE",
            'Location' => "Banque Atlantique Togo",
            'Reason' => "Demande d'habilitation. Signature numérique du document pour attester de l'authenticité de la demande",
            'ContactInfo' => 'https://www.banqueatlantique.net',
        ];

        $pdf->setSignature($certificate, $certificate_key, 'jeanpaul', '', 2, $info);

        // set default font subsetting mode
        $pdf->setFontSubsetting(true);

        // Set font
        // dejavusans is a UTF-8 Unicode font, if you only need to
        // print standard ASCII chars, you can use core fonts like
        // helvetica or times to reduce file size.
        $pdf->SetFont('times', '', 12, '', true);

        // Add a page
        // This method has several options, check the source code documentation for more information.
        $pdf->AddPage();

        $pdf->Image('images/tcpdf_signature.png', 200, 0, 10, 10, 'PNG');
        $pdf->setSignatureAppearance(200, 0, 10, 10);

        return $pdf;
    }
}